luti refactor
gerasiovM/ParticleAPI pull request #9
Opened 2023-05-13 11:33 UTC by erxson

2023-05-13 11:51 UTC, erxson commented
Еще вроде триллиард лишних this, но я их боюсь трогать

2023-05-13 11:56 UTC, gerasiovM commented
> Еще вроде триллиард лишних this, но я их боюсь трогать

Это норма, я просто как легенда зачем-то их напихал

2023-05-13 12:13 UTC, erxson commented
> > Еще вроде триллиард лишних this, но я их боюсь трогать
> 
> Это норма, я просто как легенда зачем-то их напихал

Ну могу поубирать, но не уверен, что ничего не сломаю

2023-05-13 12:13 UTC, gerasiovM requested changes
Это всё конечно хорошо, спасибо, но в разных классах по разному реализованы похожие функции. У RegularParticle.java используется ParticleSpawnEvent event, а у остальных классов Particle используется ParticleSpawnEvent particleSpawnEvent. Также в функциях spawn() у различных Particle находится if (!event.isCancelled()){}, а в ParticleGroup if (event.isCancelled()) {return;}. Также в ParticleGroup используется Bukkit.getPluginManager(), а в различных Particle используется Bukkit.getServer().getPluginManager().

2023-05-13 13:41 UTC, gerasiovM requested changes
Впринципе все очень даже хорошо, но несостыковки в реализациях похожих функций остались

2023-05-13 13:41 UTC, gerasiovM commented on src/main/java/net/gerasiov/particleapi/particles/NoteParticle.java
Не вижу особого смысла в создании отдельной переменной для местоположения партикла

2023-05-13 13:41 UTC, gerasiovM commented on src/main/java/net/gerasiov/particleapi/particles/RegularParticle.java
Проблема осталась, здесь в spawn ParticleSpawnEvent назван event, а в других партиклах назван particleSpawnEvent

2023-05-13 13:41 UTC, gerasiovM commented on src/main/java/net/gerasiov/particleapi/particles/RegularParticle.java
Также все еще PluginManager выносится в отдельную переменную, чего не делают методы spawn у других партиклов

2023-05-13 13:58 UTC, erxson commented on src/main/java/net/gerasiov/particleapi/particles/RegularParticle.java
Тогда частично отмени изменения

2023-06-06 14:21 UTC, erxson commented on src/main/java/net/gerasiov/particleapi/particles/NoteParticle.java
пон

2023-06-06 14:31 UTC, merged